name: Ergo (formerly Oragono)
repository: ircv3/ircv3.github.io
future: true
# baseurl:
exclude:
  - README.md
  - "ircd.db"
  - "ircd.yaml"
  - "tls.crt"
  - "tls.key"
plugins:
  - jekyll-sitemap
sitemap:
  file: "/sitemap.xml"
